import type { LucideProps } from "lucide-react";
import {
  ArrowRight,
  Award,
  Baby,
  BadgeCheck,
  Banknote,
  Bone,
  Brush,
  CalendarDays,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ClipboardPlus,
  GraduationCap,
  Heart,
  HeartPulse,
  Link as LinkIcon,
  LocateFixed,
  Mail,
  Medal,
  Microscope,
  MoveRight,
  Paintbrush,
  PlayCircle,
  Phone,
  ScanSearch,
  School,
  Search,
  Send,
  Share2,
  ShieldCheck,
  Sparkles,
  Star,
  Stethoscope,
  TimerReset,
  Utensils,
  Waves,
} from "lucide-react";

const iconMap = {
  verified: BadgeCheck,
  star: Star,
  arrow_forward: ArrowRight,
  open_in_new: MoveRight,
  schedule: CalendarDays,
  location_on: LocateFixed,
  call: Phone,
  search: Search,
  calendar_today: CalendarDays,
  medical_services: Stethoscope,
  payments: Banknote,
  verified_user: ShieldCheck,
  chevron_right: ChevronRight,
  east: MoveRight,
  expand_more: ChevronDown,
  mail: Mail,
  reviews: Medal,
  grade: Award,
  share: Share2,
  school: GraduationCap,
  palette: Paintbrush,
  biotech: Microscope,
  spa: Sparkles,
  health_and_safety: ShieldCheck,
  waves: Waves,
  child_care: Baby,
  "3d_rotation": ScanSearch,
  architecture: School,
  rebase_edit: ClipboardPlus,
  skeleton: Bone,
  health_metrics: HeartPulse,
  event_repeat: TimerReset,
  play_circle: PlayCircle,
  auto_fix_high: Sparkles,
  restaurant: Utensils,
  face_retouching_natural: Heart,
  precision_manufacturing: ScanSearch,
  hourglass_top: TimerReset,
  brush: Brush,
  arrow_right_alt: ArrowRight,
  link: LinkIcon,
  check_circle: CheckCircle2,
  favorite: Heart,
  lightbulb: Sparkles,
  send: Send,
} as const;

type IconName = keyof typeof iconMap;

export function SiteIcon({ name, ...props }: { name: string } & LucideProps) {
  const Icon = iconMap[name as IconName] ?? Sparkles;
  return <Icon {...props} />;
}
